[package]
name = "cynic"
version = "0.1.0"
authors = ["Graeme Coupar <grambo@grambo.me.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json-decode = { path = "../../json-decode" }
serde = "1.0.104"
serde_json = "1.0.44"
cynic-codegen = { path = "../cynic-codegen" }


[[example]]
name = "simple"
required-features = []
doc = true