[package]
name = "cynic-codegen"
version = "0.1.0"
authors = ["Graeme Coupar <graeme@polyandglot.dev>"]
edition = "2018"
homepage = "https://github.com/polyandglot/cynic"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
graphql-parser = "0.2.3"
proc-macro2 = "1.0.7"
syn = "1.0.13"
quote = "1.0.2"
Inflector = "0.11.4"

[dev-dependencies]
assert_matches = "1.3.0"
