name: Publish to crates.io

on:
  push:
    tags: ["v*"]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@1.65.0
      - name: Publish crate
        uses: katyo/publish-crates@6c200f953d803b80013520f5a7e6cc3abf9ca59a
        with:
            registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: Install markdown-extract
        shell: bash
        run: cargo install markdown-extract
      - name: Generate changelog
        shell: bash
        run: markdown-extract --no-print-matched-heading "${{ github.ref_name }}" CHANGELOG.md > release-text.md
      - name: Make GitHub release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workspace }}/release-text.md
